scraping:
  user_agent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
  timeout: 15
  retry_count: 3
  delay_between_requests: 2

weather:
  forecast_api_endpoint: "https://www.jma.go.jp/bosai/forecast/data/forecast/"
  observation_api_endpoint: "https://www.jma.go.jp/bosai/amedas/data/map/"
  # area_codeは各店舗のweather_area_codeから動的に取得
  
schedule:
  weekdays: [0, 1, 2, 3, 4, 5, 6]  # 月-日 (全曜日対象)
  hours: [9, 11, 13, 15, 17]  # 2時間毎 (9-18時の範囲で5回/日)
  business_days_only: false  # 祝日も収集対象とする

data_retention:
  days: 365  # 1年間保持

debug:
  mock_data: false  # 本番用設定
  save_responses: false