stores:
  - id: "nagoya_demo_store"
    name: "アルペンモール守山志段味店"  
    url: "https://option.junbanmachi.jp/embed/?id=2516&apiKey=Pr936rqlEoMgw0PHh2yN2t35GuzxeYyBAk24TAYlvekmYCseHCxQ3cD8beaB"
    xpath_wait_count: '//span[@class="waiting-view__number"]'
    area: "愛知県"
    weather_area_code: "230000"  # 愛知県の気象庁エリアコード
    type: "barber"
    notes: "名古屋の実際の床屋店舗例"

# 主要エリアコード参考:
# 130000: 東京都
# 140000: 神奈川県  
# 230000: 愛知県
# 270000: 大阪府
# 280000: 兵庫県
# 400000: 福岡県
